exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('module_elements').del()
    .then(function () {
      // Inserts seed entries
      return knex('module_elements').insert([
        { id: 900000, module_id: 101, type: 'heading', content: 'JavaScript for Beginners', order_num: 1 },
        { id: 900001, module_id: 101, type: 'paragraph', content: "JavaScript, as you might know, is ubiquitous in today’s software development world. It is the foundation of frontend web development and is the key ingredient in frameworks like ReactJS, Angular, and VueJS. It can also help create solid backends with platforms like Nodejs, runs desktop applications like Slack, Atom, and Spotify, and runs on mobile phones as Progressive Web Apps (PWAs). \n In short, it is everywhere—and for good reasons. For starters, compared to other languages like C and Java, JavaScript is generally easier to learn. When we say ‘easier’, we mean in terms of how quickly you can go from being a JavaScript novice to someone who can actually make a living writing professional, high quality JavaScript code. So, in that sense, it’s more accessible than some other languages like C and Java. \n JavaScript is also a fun and rewarding language, which is especially important when you’re just getting started in software development. The community support is very good, so if you get stuck, there’s a good chance that the problem and its solution already exist on the web.", order_num: 2 },
        { id: 900002, module_id: 101, type: 'paragraph', content: "JavaScript is a programming language, and like most programming languages, it has some basic constructs that we’ll look at. A program in JavaScript is like a sequence of steps. Similar to how we give directions to a stranger, a computer needs detailed instructions, defined as steps, to accomplish any simple or complex action. \n JavaScript can also be used as a calculator. In fact, a lot of the code you’ll see in the wild will have basic calculations everywhere. It supports all the regular functions, called operators, like plus (+), minus (-), multiply (*), divide (/) and so on.", order_num: 3 },
        { id: 900003, module_id: 101, type: 'link', content: 'https://careerfoundry.com/en/tutorials/web-development-for-beginners/an-introduction-to-javascript/', order_num: 4 },
        { id: 900004, module_id: 101, type: 'video', content: 'https://www.youtube.com/embed/W6NZfCO5SIk', order_num: 5 },

        { id: 900005, module_id: 102, type: 'heading', content: 'C++ for Beginners', order_num: 1 },
        { id: 900006, module_id: 102, type: 'paragraph', content: "C++ is known to be a very powerful language. C++ allows you to have a lot of control as to how you use computer resources, so in the right hands its speed and ability to cheaply use resources should be able to surpass other languages. Thanks to C++'s performance, it is often used to develop game engines, games, and desktop apps. Many AAA title video games are built with C++.", order_num: 2 },
        { id: 900007, module_id: 102, type: 'paragraph', content: "C++ (pronounced see plus plus) was developed by Bjarne Stroustrup at Bell Labs as an extension to C, starting in 1979. C++ adds many new features to the C language, and is perhaps best thought of as a superset of C, though this is not strictly true (as C99 introduced a few features that do not exist in C++). C++’s claim to fame results primarily from the fact that it is an object-oriented language. As for what an object is and how it differs from traditional programming methods, well, we’ll cover that in chapter 8 (Basic object-oriented programming). \n C++ was standardized in 1998 by the ISO committee (this means the ISO committee ratified a document describing the C++ language, to help ensure all compilers adhered to the same set of standards). A minor update was released in 2003 (called C++03). \n Three major updates to the C++ language (C++11, C++14, and C++17, ratified in 2011, 2014, and 2017 accordingly) have been made since then, each adding additional functionality. C++11 in particular added a huge number of new capabilities, and at this point is widely considered the new baseline. As of the time of writing, C++20 is in the works, promising to bring even more new capabilities. Future upgrades to the language are expected every three or so years. /n Each new formal release of the language is called a language standard (or language specification). Standards are named after the year they are released in. For example, there is no C++15, because there was no new standard in 2015.", order_num: 3 },
        { id: 900008, module_id: 102, type: 'link', content: 'https://www.learncpp.com/', order_num: 4 },
        { id: 900009, module_id: 102, type: 'video', content: 'https://www.youtube.com/embed/vLnPwxZdW4Y&vl=en', order_num: 5 },

        { id: 900010, module_id: 103, type: 'heading', content: 'Why Learn C# (CSharp)?', order_num: 1 },
        { id: 900011, module_id: 103, type: 'paragraph', content: "C# is a general-purpose, modern and object-oriented programming language pronounced as “C sharp”. It was developed by Microsoft led by Anders Hejlsberg and his team within the .Net initiative and was approved by the European Computer Manufacturers Association (ECMA) and International Standards Organization (ISO). C# is among the languages for Common Language Infrastructure and the current version of C# is version 7.2. C# is a lot similar to Java syntactically and is easy for the users who have knowledge of C, C++ or Java.", order_num: 2 },
        { id: 900012, module_id: 103, type: 'paragraph', content: "C# has many other reasons for being popular and in demand. \n Easy To Start: \n C# is a high-level language so it is closer to other popular programming languages like C, C++, and Java and thus becomes easy to learn for anyone. \n Widely used for developing Desktop and Web Application: \n C# is widely used for developing web applications and Desktop applications. It is one of the most popular languages that is used in professional desktop. If anyone wants to create Microsoft apps, C# is their first choice.", order_num: 3 },
        { id: 900013, module_id: 103, type: 'link', content: 'https://csharp.net-tutorials.com/getting-started/introduction/', order_num: 4 },
        { id: 900014, module_id: 103, type: 'video', content: 'https://www.youtube.com/embed/GhQdlIFylQ8', order_num: 5 },

        { id: 900015, module_id: 104, type: 'heading', content: 'Introduction to Ruby', order_num: 1 },
        { id: 900016, module_id: 104, type: 'paragraph', content: 'In this course, you will gain familiarity with Ruby and basic programming concepts—including variables, loops, control flow, and most importantly, object-oriented programming. You’ll get a chance to test your understanding in a final project, which you’ll build locally.', order_num: 2 },
        { id: 900017, module_id: 104, type: 'paragraph', content: "In Ruby, your information (or data) can come in different types. There are three data types in Ruby that we’re interested in right now: Numeric (any number), Boolean (which can be true or false), and String (words or phrases like 'I'm learning Ruby!').Computer programs exist to quickly analyze and manipulate data. For that reason, it’s important for us to understand the different data types that we can use in our programs. Reminder: never use quotation marks with booleans, or Ruby will think you’re talking about a string (a word or phrase) instead of a value that can be true or false. It’s also important to remember that Ruby is case-sensitive (it cares about capitalization).", order_num: 3 },
        { id: 900018, module_id: 104, type: 'link', content: 'https://www.codecademy.com/courses/learn-ruby/lessons/introduction-to-ruby/exercises/data-types-numbers-strings-booleans', order_num: 4 },
        { id: 900019, module_id: 104, type: 'video', content: 'https://www.youtube.com/embed/8wZ2ZD--VTk', order_num: 5 },

        { id: 900020, module_id: 105, type: 'heading', content: 'Introduction to Python', order_num: 1 },
        { id: 900021, module_id: 105, type: 'paragraph', content: "Welcome! Are you completely new to programming? If not then we presume you will be looking for information about why and how to get started with Python. Fortunately an experienced programmer in any programming language (whatever it may be) can pick up Python very quickly. It's also easy for beginners to use and learn, so jump in!", order_num: 2 },
        { id: 900022, module_id: 105, type: 'paragraph', content: 'Python is completely object oriented, and not "statically typed". You do not need to declare variables before using them, or declare their type. Every variable in Python is an object. \n Numbers: \n Python supports two types of numbers - integers and floating point numbers.', order_num: 3 },
        { id: 900023, module_id: 105, type: 'link', content: 'https://www.learnpython.org/', order_num: 4 },
        { id: 900024, module_id: 105, type: 'video', content: 'https://www.youtube.com/embed/rfscVS0vtbw', order_num: 5 },

        { id: 900025, module_id: 106, type: 'heading', content: 'JavaScript with React', order_num: 1 },
        { id: 900026, module_id: 106, type: 'paragraph', content: "React is a declarative, efficient, and flexible JavaScript library for building user interfaces. It lets you compose complex UIs from small and isolated pieces of code called “components”. \n The render method returns a description of what you want to see on the screen. React takes the description and displays the result. In particular, render returns a React element, which is a lightweight description of what to render. Most React developers use a special syntax called “JSX” which makes these structures easier to write. The <div /> syntax is transformed at build time to React.createElement('div')", order_num: 2 },
        { id: 900027, module_id: 106, type: 'paragraph', content: "State is used to deal with dynamic information (as is props). \n Unlike props, a component’s state is not passed in from the outside. To make a component have state you must give the component a state property (which should be declared inside of constructor method", order_num: 3 },
        { id: 900028, module_id: 106, type: 'link', content: 'https://reactjs.org/tutorial/tutorial.html', order_num: 4 },
        { id: 900029, module_id: 106, type: 'video', content: 'https://www.youtube.com/embed/Ke90Tje7VS0', order_num: 5 },

        { id: 900030, module_id: 107, type: 'heading', content: 'Redux - ', order_num: 1 },
        { id: 900031, module_id: 107, type: 'paragraph', content: 'Redux is one of the hottest libraries in front-end development these days. However, many people are confused about what it is and what its benefits are. As the documentation states, Redux is a predictable state container for JavaScript apps. To rephrase that, it’s an application data-flow architecture, rather than a traditional library or a framework like Underscore.js and AngularJS.', order_num: 2 },
        { id: 900032, module_id: 107, type: 'paragraph', content: 'Redux was created by Dan Abramov around June 2015. It was inspired by Facebook’s Flux and functional programming language Elm. Redux got popular very quickly because of its simplicity, small size (only 2 KB) and great documentation. For more information check out the link below and make sure to watch the introductory video', order_num: 3 },
        { id: 900033, module_id: 107, type: 'link', content: 'https://medium.com/javascript-in-plain-english/the-only-introduction-to-redux-and-react-redux-youll-ever-need-8ce5da9e53c6', order_num: 4 },
        { id: 900034, module_id: 107, type: 'video', content: 'https://www.youtube.com/embed/CVpUuw9XSjY', order_num: 5 },

        { id: 900035, module_id: 108, type: 'heading', content: 'Step 1: Warm Up', order_num: 1 },
        { id: 900036, module_id: 108, type: 'paragraph', content: "Warm up with some Squarehouse Kicks. They are considered easier as you can use the corners of the square as reference points.", order_num: 2 },
        { id: 900037, module_id: 108, type: 'paragraph', content: 'Once you are warm, never get cold. There are 5 types of Roundhouse Kick, and Coldhouse Kick is not one of them.', order_num: 3 },
        { id: 900038, module_id: 108, type: 'link', content: 'https://lmgtfy.app/?q=cold+house+kicks', order_num: 4 },
        { id: 900039, module_id: 108, type: 'video', content: 'https://www.youtube.com/embed/BtnwY-j091A', order_num: 5 },
        { id: 900040, module_id: 108, type: 'heading', content: 'Step 2: Find Something To Kick', order_num: 6 },
        { id: 900041, module_id: 108, type: 'paragraph', content: 'Kick, Kick, Kick some more', order_num: 7 },
        { id: 900042, module_id: 108, type: 'paragraph', content: 'Move on to Roundhouse Kicks', order_num: 8},{ id: 900043, module_id: 108, type: 'link', content: 'https://breakingmuscle.com/fitness/muay-thai-workout-how-to-train-the-roundhouse-kick', order_num: 9 },
        { id: 900044, module_id: 108, type: 'video', content: 'https://www.youtube.com/embed/y1gaWl8EllQ', order_num: 10 },
        { id: 900045, module_id: 109, type: 'heading', content: 'Step 1: Overcoming Your Fear Of CSS', order_num: 1 },
        { id: 900046, module_id: 109, type: 'paragraph', content: "There are three ways to apply CSS to HTML: Inline, internal, and external. \n Inline: \n Inline styles are plonked straight into the HTML tags using the style attribute. \n Internal \n Embedded, or internal, styles are used for the whole page. Inside the head element, the style tags surround all of the styles for the page. \n Although preferable to soiling our HTML with inline presentation, it is similarly usually preferable to keep the HTML and the CSS files separate, and so we are left with our savior… \n External \n External styles are used for the whole, multiple-page website. There is a separate CSS file, If this file is saved as “style.css” in the same directory as your HTML page then it can be linked to in the HTML", order_num: 2 },
        { id: 900047, module_id: 109, type: 'paragraph', content: 'CSS (Cascading Style Sheets) was a technology recommended by the World Wide Web Consortium (W3C) in 1996. An easy way to understand the purpose of CSS is to view it as an addition to HTML that helps simplify and improve web page design. In fact, some CSS effects are not possible via HTML alone. \n Another advantage of CSS is that it allows you to specify a style once, but the browser can apply that style many times in a document. For example, if you want some of the pictures displayed in your website to have a thin, blue frame around them, you can define this frame as a style in your CSS. Then, instead of having to repeat an HTML definition of the thin and blue frame — each and every time you want that particular frame — you can merely insert the CSS style as an attribute for each graphic element that you want framed.', order_num: 3 },
        { id: 900048, module_id: 109, type: 'link', content: 'https://www.dummies.com/web-design-development/site-development/css-web-design-for-dummies-cheat-sheet/', order_num: 4 },
        { id: 900049, module_id: 109, type: 'video', content: 'https://www.youtube.com/embed/1Rs2ND1ryYc', order_num: 5 },
        { id: 900050, module_id: 110, type: 'heading', content: "Step 1: HTML - What is it? We just don't know!", order_num: 1 },
        { id: 900051, module_id: 110, type: 'paragraph', content: "The primary thing to keep in mind, the supermagic key, is that HTML is used for meaning and CSS is used for presentation. HTML is nothing more than fancy structured content and the visual formatting of that content will come later when we tackle CSS.", order_num: 2 },
        { id: 900052, module_id: 110, type: 'paragraph', content: 'HTML files are nothing more than simple text files, so to start writing in HTML, you need nothing more than a simple text editor. \n Notepad is a common text editor on Windows-based computers (usually found under the Programs > Accessories menu) and Mac OSX computers come bundled with TextEdit but any program that lets you fiddle with text will do. \n To look at HTML files, they don’t even need to be on the web. Open a web browser such as Chrome, Firefox, Safari or Internet Explorer and in the address bar, where you usually type web addresses, type in the location of the file you just saved (for example, “c:\html\myfirstpage.html”) and hit return. Alternatively, go to the File menu of the browser, select Open, and browse for the file. \n Pow. There it is. Your first web page. How exciting. And all it took was a few typed words. \n For more information of HTML check out the link below and this informative video', order_num: 3 },
        { id: 900053, module_id: 110, type: 'link', content: 'https://htmldog.com/guides/html/beginner/', order_num: 4 },
        { id: 900054, module_id: 110, type: 'video', content: 'https://www.youtube.com/embed/UB1O30fR-EE', order_num: 5 }
      ])
    })
}
